# Generated by Django 3.2.6 on 2021-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bonus_course_department_salgrade_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=10)),
                ('mgr', models.IntegerField()),
                ('sal', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('deptno', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
